# Generated by Django 2.2.4 on 2019-09-02 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'permissions': (('pode_mudar_nota', 'Pode mudar nota'),)},
        ),
    ]
