# Generated by Django 2.2.4 on 2019-09-01 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(max_length=5, verbose_name='nota')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AvaliacaoProAluno', to=settings.AUTH_USER_MODEL, verbose_name='professor')),
            ],
        ),
    ]
