# Generated by Django 2.2.4 on 2019-09-02 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='data_avaliacao',
            new_name='created_at',
        ),
    ]
