# Generated by Django 2.2.4 on 2019-09-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0003_auto_20190901_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='realisacao',
            field=models.DateTimeField(),
        ),
    ]
