# Generated by Django 2.2.4 on 2019-09-02 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0004_auto_20190901_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliacao', 'verbose_name_plural': 'Avaliacoes'},
        ),
    ]
