# Generated by Django 2.2.4 on 2019-09-02 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0005_auto_20190901_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacaoFromAluno', to='users.Aluno', verbose_name='nota_aluno'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacaoFromProfessor', to='users.Professor', verbose_name='nota_professor'),
        ),
    ]
